CREATE TABLE COUNTRY(
    NAME VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY_KEY_COUNTRY PRIMARY KEY(NAME)
);

CREATE TABLE CUSTOMER(
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    IBAN VARCHAR(34) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY_KEY_CUSTOMER PRIMARY KEY(EMAIL),
    CONSTRAINT FOREIGN_KEY_CUSTOMER FOREIGN KEY(COUNTRY)
                     REFERENCES COUNTRY(NAME)
);